"""Add cubic_rate to offers

Revision ID: f4976483ee19
Revises: e9a2b7b58cf7
Create Date: 2024-05-28

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4976483ee19'
down_revision = 'e9a2b7b58cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('cubic_rate', sa.Float(), nullable=True))

    # Ensure no NULL values in extra_cost_per_kg and min_charge columns
    op.execute('UPDATE offer SET extra_cost_per_kg = 0 WHERE extra_cost_per_kg IS NULL')
    op.execute('UPDATE offer SET min_charge = 0 WHERE min_charge IS NULL')

    # Alter columns to NOT NULL after updating existing NULL values
    op.alter_column('offer', 'extra_cost_per_kg',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_nullable=True)
    op.alter_column('offer', 'min_charge',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_nullable=True)
    
    op.alter_column('offer', 'company',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.alter_column('offer', 'destination',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', 'min_charge',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('offer', 'extra_cost_per_kg',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('offer', 'destination',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('offer', 'company',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('offer', 'cubic_rate')
    # ### end Alembic commands ###
