"""Update PostalCode schema

Revision ID: 156e81b42dcc
Revises: e2e779e9c5a5
Create Date: 2024-06-02 23:41:14.180314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '156e81b42dcc'
down_revision = 'e2e779e9c5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postal_code', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postal_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
