"""Fix relationships in models

Revision ID: 2a473f8c74dc
Revises: a8e10b25338a
Create Date: 2024-06-03 21:50:51.190172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a473f8c74dc'
down_revision = 'a8e10b25338a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.alter_column('offer_type',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('weight', 'volume'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.alter_column('offer_type',
               existing_type=sa.Enum('weight', 'volume'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
