"""Added max_volumetric_weight to Company

Revision ID: 69b14f4b849c
Revises: a20b04fd1eaf
Create Date: 2024-06-03 07:13:57.052691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b14f4b849c'
down_revision = 'a20b04fd1eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_volumetric_weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('max_volumetric_weight')

    # ### end Alembic commands ###
