"""Update Offer model

Revision ID: 92d811c0f296
Revises: 69b14f4b849c
Create Date: 2024-06-03 10:11:55.888848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92d811c0f296'
down_revision = '69b14f4b849c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_column('destination')

    with op.batch_alter_table('postal_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postal_code', schema=None) as batch_op:
        batch_op.drop_column('city')

    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', mysql.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
