"""Fix relationships in models

Revision ID: 94d645e0bdb8
Revises: 69189d83f8cb
Create Date: 2024-06-03 22:31:11.206882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94d645e0bdb8'
down_revision = '69189d83f8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('courier', 'transport'), nullable=False))
        batch_op.add_column(sa.Column('max_length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_volumetric_weight', sa.Float(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('postal_code', schema=None) as batch_op:
        batch_op.alter_column('area_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('prefecture',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postal_code', schema=None) as batch_op:
        batch_op.alter_column('prefecture',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('area_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('max_volumetric_weight')
        batch_op.drop_column('max_weight')
        batch_op.drop_column('max_height')
        batch_op.drop_column('max_width')
        batch_op.drop_column('max_length')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
