"""Update Offer model

Revision ID: d68898a2506b
Revises: 92d811c0f296
Create Date: 2024-06-03 20:09:46.775505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68898a2506b'
down_revision = '92d811c0f296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_column('offer_type')

    # ### end Alembic commands ###
